# Exercício 1

Os blocos lógicos try, catch e finally são usados em contextos de tratamento de exceções (geralmente erros causados pela interação com o usuário).

Sendo assim, o bloco try consiste da demarcação de uma área do programa em que é possível/esperada a ocorrência de uma exceção. Por sua vez, o bloco catch tem como função a &quot;captura&quot; de uma exceção ocorrida anteriormente, geralmente dentro de um bloco try, assim como a demarcação de um código direcionado para o tratamento (solução) da exceção em questão.

Paralelamente aos blocos try e catch, o bloco finally tem como função executar um pedaço de código de forma independente dos resultados dos blocos citados anteriormente, ou seja, o código presente no finally será executado caso uma exceção ocorra no try e seja tratada no catch, assim como se nenhuma exceção ocorrer no try e, consequentemente, o catch nem ser executado.
